[alias]
mayo1 = "run --no-default-features --features mayo1 --release"
mayo2 = "run --no-default-features --features mayo2 --release"
mayo3 = "run --no-default-features --features mayo3 --release"
mayo5 = "run --no-default-features --features mayo5 --release"

bench_mayo1 = "bench --no-default-features --features mayo1 --bench my_benchmark -- --verbose"
bench_mayo2 = "bench --no-default-features --features mayo2 --bench my_benchmark -- --verbose"
bench_mayo3 = "bench --no-default-features --features mayo3 --bench my_benchmark -- --verbose"
bench_mayo5 = "bench --no-default-features --features mayo5 --bench my_benchmark -- --verbose"

