[alias]
mayo1 = "run --no-default-features --features mayo1 --release"
mayo2 = "run --no-default-features --features mayo2 --release"
mayo3 = "run --no-default-features --features mayo3 --release"
mayo5 = "run --no-default-features --features mayo5 --release"

mayo1_aes = "run --no-default-features --features mayo1,system_aes --release"
mayo2_aes = "run --no-default-features --features mayo2,system_aes --release"
mayo3_aes = "run --no-default-features --features mayo3,system_aes --release"
mayo5_aes = "run --no-default-features --features mayo5,system_aes --release"

bench_mayo1 = "bench --no-default-features --features mayo1 --bench benchmark -- --verbose"
bench_mayo2 = "bench --no-default-features --features mayo2 --bench benchmark -- --verbose"
bench_mayo3 = "bench --no-default-features --features mayo3 --bench benchmark -- --verbose"
bench_mayo5 = "bench --no-default-features --features mayo5 --bench benchmark -- --verbose"

bench_mayo1_aes = "bench --no-default-features --features mayo1,system_aes --bench benchmark -- --verbose"
bench_mayo2_aes = "bench --no-default-features --features mayo2,system_aes --bench benchmark -- --verbose"
bench_mayo3_aes = "bench --no-default-features --features mayo3,system_aes --bench benchmark -- --verbose"
bench_mayo5_aes = "bench --no-default-features --features mayo5,system_aes --bench benchmark -- --verbose"




[target.'cfg(target_os = "windows")']
rustflags = ["-C", "link-args=/STACK:67108864"] # 64 MB in bytes

#[target.'cfg(target_os = "macos")']
#rustflags = ["-C", "link-arg=-Wl,-stack_size,0x4000000"] # 64 MB in hexadecimal
