[alias]
mayo1 = "run --no-default-features --features mayo1,custom_stack --release"
mayo2 = "run --no-default-features --features mayo2,custom_stack --release"
mayo3 = "run --no-default-features --features mayo3,custom_stack --release"
mayo5 = "run --no-default-features --features mayo5,custom_stack --release"

mayo1_aes = "run --no-default-features --features mayo1,custom_stack, system_aes --release"
mayo2_aes = "run --no-default-features --features mayo2,custom_stack, system_aes --release"
mayo3_aes = "run --no-default-features --features mayo3,custom_stack, system_aes --release"
mayo5_aes = "run --no-default-features --features mayo5,custom_stack, system_aes --release"

bench_mayo1 = "run --no-default-features --features mayo1,bench --release"
bench_mayo2 = "run --no-default-features --features mayo2,bench --release"
bench_mayo3 = "run --no-default-features --features mayo3,bench --release"
bench_mayo5 = "run --no-default-features --features mayo5,bench --release"

bench_mayo1_aes = "bench --no-default-features --features mayo1,system_aes --bench benchmark -- --verbose"
bench_mayo2_aes = "bench --no-default-features --features mayo2,system_aes --bench benchmark -- --verbose"
bench_mayo3_aes = "bench --no-default-features --features mayo3,system_aes --bench benchmark -- --verbose"
bench_mayo5_aes = "bench --no-default-features --features mayo5,system_aes --bench benchmark -- --verbose"

[target.'cfg(all(target_os = "windows", feature = "custom_stack"))']
rustflags = ["-C", "link-args=/STACK:4194304"] # 4MB

[target.'cfg(all(target_os = "macos", feature = "custom_stack"))']
rustflags = ["-C", "link-arg=-Wl,-stack_size,0x400000"] # 4MB